# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: schoolwork
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: quiztopia
# "service" is the name of this project. This will also be added to your AWS resource names.
service: quiz

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    SECRET: ${env:SECRET}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/UsersTable"
        # - "arn:aws:dynamodb:${self:provider.region}:*:table/UsersTable/index/*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    UsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UsernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
