# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: schoolwork
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: quiztopia
# "service" is the name of this project. This will also be added to your AWS resource names.
service: quiz

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    SECRET: ${env:SECRET}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/QUsersTable"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/QuizTable"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/QUsersTable/index/*"

functions:
  signup:
    handler: functions/signup/index.handler
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: /login
          method: post

  getUser:
    handler: functions/getUser/index.handler
    events:
      - httpApi:
          path: /user
          method: get

  postQuiz:
    handler: functions/postQuiz/index.handler
    events:
      - httpApi:
          path: /quiz
          method: post

  getAllQuiz:
    handler: functions/getAllQuiz/index.handler
    events:
      - httpApi:
          path: /quiz
          method: get

  postQuestion:
    handler: functions/postQuestion/index.handler
    events:
      - httpApi:
          path: /quiz/question
          method: post

  getSpecificQuiz:
    handler: functions/getSpecificQuiz/index.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: get

resources:
  Resources:
    QUsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: QUsersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: QUsernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    QuizTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: QuizTable
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: quizname
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: QuizIndex
            KeySchema:
              - AttributeName: quizname
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    leaderboardTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: leaderboardTable
        AttributeDefinitions:
          - AttributeName: leaderboardId
            AttributeType: S
        KeySchema:
          - AttributeName: leaderboardId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
